segmentation:
  type:
    default: contiguous
    type: "string"
    description: "The segmentation type. 'contiguous' refers to end-to-end, disjoint sections of the sequence without overlaps."
    constraints:
      options: ["contiguous", "random"]
  min_length:
    default: 0
    type: "integer"
    description: "The minimum length of a segment. Segments shorter than this value will be discarded."
    constraints:
      min: 0
  max_length:
    default: 512
    type: "integer"
    description: "The maximum allowable segment length."
    constraints:
      min: 0
  coverage:
    default: 1.0
    type: "float"
    description: "The expected number of times that segmen covers the original sequence. It is only valid for type=random. Beaware, that it is sampled from uniform distribution, therefore the at the two ends of the sueqnce the coverage will differ."
    constraints:
      min: 0.0
      max: 100.0 # Too much coverage 

tokenization:
  type:
    default: lca
    type: "string"
    description: "The tokenization solution. The default is the LCA (Local Context Aware) tokenization."
    constraints:
      options: ["lca"]
  kmer:
    default: 6
    type: "integer"
    description: "The k-mer size used during the tokenization process."
    constraints:
      options: [1, 2, 3, 4, 5, 6, 7, 8, 9]
  shift:
    default: 1
    type: "integer"
    description: "The k-mer shift parameter. Default is 1. "
    constraints:
      min: 0
  max_segment_length: #
    default: 
    type: "integer"
    description: "The maximum number of characters in the segment. It should be aligned with the language model. This pramrter is interchangable with token_limit"
    constraints:
      min: 6
      max: 1027 #(max_token_counts-3)*shift + kmer
  token_limit: 
    default: 
    type: "integer"
    description: "The maximum number of tokens that the the LM could handle. It includes the special tokens such as CLS and SEP This pramrter is interchangable with max_segment_length."
    constraints:
      min: 1
      max: 1024 # That's our current limit
  max_unknown_token_proportion: 
    default: 
    type: "float"
    description: "The maximum proportion of unknown tokens in a max length sequence."
    constraints:
      min: 0
      max: 1

      